/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package nutricionista.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nutricionista.accesoDatos.IngredienteData;
import nutricionista.entidades.Ingrediente;

/**
 *
 * @author Hernan
 */
public class ListaDeIngredietes extends javax.swing.JInternalFrame {

    private List<Ingrediente> listaIngredientes;
    private IngredienteData ingredienteData;
    private Ingrediente ingrediente = null;
    private Ingrediente ingrediente2 = null;
    private DefaultTableModel modelo;

    /**
     * Creates new form NewJInternalFrame
     */
    public ListaDeIngredietes() {
        initComponents();
        modelo = new DefaultTableModel();
        ingredienteData = new IngredienteData();
        listaIngredientes = ingredienteData.listaDeIngredientes();
        cabeceradeTabla();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaDeIngredientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtIngredientes = new javax.swing.JTable();
        jbAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        ListaDeIngredientes.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        ListaDeIngredientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ListaDeIngredientes.setText("Lista de Ingredientes");

        jtIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtIngredientes);

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
<<<<<<< Updated upstream:GP13Nutricionista/src/nutricionista/vistas/ListaDeIngredientes.java
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
=======
                .addContainerGap(170, Short.MAX_VALUE)
>>>>>>> Stashed changes:GP13Nutricionista/src/nutricionista/vistas/ListaDeIngredietes.java
                .addComponent(jbAgregar)
                .addGap(18, 18, 18)
                .addComponent(jbModificar)
                .addGap(18, 18, 18)
                .addComponent(jbEliminar)
<<<<<<< Updated upstream:GP13Nutricionista/src/nutricionista/vistas/ListaDeIngredientes.java
                .addGap(100, 100, 100)
=======
                .addGap(145, 145, 145)
>>>>>>> Stashed changes:GP13Nutricionista/src/nutricionista/vistas/ListaDeIngredietes.java
                .addComponent(jbSalir)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaDeIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
<<<<<<< Updated upstream:GP13Nutricionista/src/nutricionista/vistas/ListaDeIngredientes.java
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
=======
                .addGap(106, 106, 106)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> Stashed changes:GP13Nutricionista/src/nutricionista/vistas/ListaDeIngredietes.java
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaDeIngredientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbModificar)
                        .addComponent(jbAgregar)
                        .addComponent(jbEliminar))
                    .addComponent(jbSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        FormularioIngrediente formularioIngrediente = new FormularioIngrediente(ingrediente);
        menuPrincipal.jDesktopPane1.add(formularioIngrediente);
        formularioIngrediente.moveToFront();
        formularioIngrediente.setVisible(true);
        formularioIngrediente.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        int filaElegida = jtIngredientes.getSelectedRow();
        if (filaElegida != -1) {
            ingrediente2 = null;
            int id = Integer.parseInt(jtIngredientes.getValueAt(filaElegida, 0).toString());
            String nombre = jtIngredientes.getValueAt(filaElegida, 1).toString();
            ingrediente2 = new Ingrediente (id,nombre);
            FormularioIngrediente formularioIngrediente = new FormularioIngrediente(ingrediente2);
            menuPrincipal.jDesktopPane1.add(formularioIngrediente);
            formularioIngrediente.moveToFront();
            formularioIngrediente.setVisible(true);
            formularioIngrediente.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        } else {
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada, seleccione una para modificar ese ingrediente.");
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        int filaElegida = jtIngredientes.getSelectedRow();
        if (filaElegida != -1) {
            int idIngrediente = Integer.parseInt(jtIngredientes.getValueAt(filaElegida, 0).toString());
            String nombreIngrediente = jtIngredientes.getValueAt(filaElegida, 1).toString();
            ingrediente = new Ingrediente(idIngrediente, nombreIngrediente);
            ingredienteData.eliminarIngrediente(ingrediente);
            ingrediente = null;
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void cabeceradeTabla() {
        ArrayList<Object> cabecera = new ArrayList<>();
        cabecera.add("ID");
        cabecera.add("Nombre del Ingrediente");
        for (Object it : cabecera) {
            modelo.addColumn(it);
        }
        jtIngredientes.setModel(modelo);
    }

    private void cargarTabla() {
        for (Ingrediente i : listaIngredientes) {
            modelo.addRow(new Object[]{i.getIdIngrediente(), i.getNomIngrediente()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListaDeIngredientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTable jtIngredientes;
    // End of variables declaration//GEN-END:variables
}
