/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package nutricionista.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nutricionista.accesoDatos.IngredienteData;
import nutricionista.entidades.Ingrediente;

/**
 *
 * @author Hernan
 */
public class ListaDeIngredietes extends javax.swing.JInternalFrame {

    private List<Ingrediente> listaIngredientes;
    private IngredienteData ingredienteData;
    private Ingrediente ingrediente = null;
    private Ingrediente ingrediente2 = null;

    /**
     * Creates new form NewJInternalFrame
     */
    public ListaDeIngredietes() {
        initComponents();
        ingredienteData = new IngredienteData();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ListaDeIngredientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtIngredientes = new javax.swing.JTable();
        jbAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(621, 438));

        ListaDeIngredientes.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        ListaDeIngredientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ListaDeIngredientes.setText("Lista de Ingredientes");

        jtIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtIngredientes.setEditingColumn(0);
        jtIngredientes.setEditingRow(0);
        jtIngredientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtIngredientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtIngredientes);
        jtIngredientes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaDeIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(175, 175, 175)
                        .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ListaDeIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        CrearIngrediente jframe = new CrearIngrediente(this);
        jframe.setSize(423, 303);
        jframe.setLocationRelativeTo(null);
        jframe.setVisible(true);
        jframe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        int filaElegida = jtIngredientes.getSelectedRow();
        if (filaElegida != -1) {
            ingrediente2 = null;
            int id = Integer.parseInt(jtIngredientes.getValueAt(filaElegida, 0).toString());
            String nombre = jtIngredientes.getValueAt(filaElegida, 1).toString();
            ingrediente2 = new Ingrediente (id,nombre);
            ModificarIngrediente jframe = new ModificarIngrediente(nombre, id,this);
            jframe.setSize(423, 303);
            jframe.setLocationRelativeTo(null);
            jframe.setVisible(true);
            jframe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } else {
            JOptionPane.showMessageDialog(null, "No hay ninguna fila seleccionada, seleccione una para modificar ese ingrediente.");
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        int filaElegida = jtIngredientes.getSelectedRow();
        if (filaElegida != -1) {
            Object[] opciones = {"Sí", "No"};
            int confirmacion = JOptionPane.showOptionDialog(
                this,
                "¿Desea eliminar el ingrediente seleccionado?",
                "Confirmación de eliminación",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // Icono personalizado (null para el predeterminado)
                opciones, // Botones personalizados
                opciones[0] // Botón predeterminado
            );

            if (confirmacion == JOptionPane.YES_OPTION) {
                try {
                    int idIngrediente = Integer.parseInt(jtIngredientes.getValueAt(filaElegida, 0).toString());
                    String nombreIngrediente = jtIngredientes.getValueAt(filaElegida, 1).toString();
                    Ingrediente ingrediente = new Ingrediente(idIngrediente, nombreIngrediente);

                    ingredienteData.eliminarIngrediente(ingrediente); // Método para eliminar el ingrediente de la BD

                    ingrediente = null; // Limpiamos la referencia
                    this.limpioTabla(); // Limpia la tabla actual
                    this.cargarTabla(); // Recarga la tabla actualizada
                } catch (NumberFormatException | NullPointerException ex) {
                    JOptionPane.showMessageDialog(
                        this,
                        "Error al procesar la información del ingrediente: " + ex.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Debe seleccionar un ingrediente para eliminar.",
                "Advertencia",
                JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed



    public void cargarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        ArrayList<Object> cabecera = new ArrayList<>();
        cabecera.add("ID");
        cabecera.add("Nombre del Ingrediente");
        for (Object it : cabecera) {
            modelo.addColumn(it);
        }
        jtIngredientes.setModel(modelo);
        listaIngredientes = ingredienteData.listaDeIngredientes();
        for (Ingrediente i : listaIngredientes) {
            modelo.addRow(new Object[]{i.getIdIngrediente(), i.getNomIngrediente()});
        }
    }
    
    public void limpioTabla(){
        listaIngredientes = new ArrayList();
        jtIngredientes.setModel(new DefaultTableModel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ListaDeIngredientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTable jtIngredientes;
    // End of variables declaration//GEN-END:variables
}
